Repository 4-404-Not-Found/deventer, pull requests merged in 2024-06, with the labels that each got.

#77 AdminUserController 구현
  src/main/java/com/sparta/deventer/controller/AdminUserController.java
Labels: feat

#79 feat: Github 소셜로그인 기능 구현
  src/main/java/com/sparta/deventer/controller/AuthController.java
  src/main/java/com/sparta/deventer/dto/GitHubTokenResponseDto.java
  src/main/java/com/sparta/deventer/dto/GitHubUserDto.java
  src/main/java/com/sparta/deventer/exception/GitHubTokenException.java
  src/main/java/com/sparta/deventer/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/deventer/repository/UserRepository.java
  src/main/java/com/sparta/deventer/service/AuthService.java
  src/main/resources/application.properties
  src/test/java/com/sparta/deventer/DeventerApplicationTests.java
Labels: feat

#81 관리자가 사용자 대상으로 실행할 수 있는 기능 추가
  .idea/modules.xml
  src/main/java/com/sparta/deventer/controller/AdminUserController.java
  src/main/java/com/sparta/deventer/dto/ChangeNicknameRequestDto.java
  src/main/java/com/sparta/deventer/dto/UserResponseDto.java
  src/main/java/com/sparta/deventer/entity/User.java
  src/main/java/com/sparta/deventer/enums/UserRole.java
  src/main/java/com/sparta/deventer/enums/UserStatus.java
  src/main/java/com/sparta/deventer/exception/InvalidOperationException.java
  src/main/java/com/sparta/deventer/service/AdminUserService.java
Labels: feat, refactor

#89 Refactor/GitHub login & Category
  api-test/client-test.http
  src/main/java/com/sparta/deventer/entity/User.java
  src/main/java/com/sparta/deventer/enums/UserLoginType.java
  src/main/java/com/sparta/deventer/exception/DuplicateException.java
  src/main/java/com/sparta/deventer/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/deventer/exception/UserInfoDuplicateException.java
  src/main/java/com/sparta/deventer/repository/UserRepository.java
  src/main/java/com/sparta/deventer/service/AuthService.java
  src/main/java/com/sparta/deventer/service/CategoryService.java
  src/main/resources/application.properties
Labels: refactor

#91 사용자의 스크랩 목록 조회 및 스크랩 도메인 리팩토링
  src/main/java/com/sparta/deventer/controller/ScrapController.java
  src/main/java/com/sparta/deventer/dto/ScrapResponseDto.java
  src/main/java/com/sparta/deventer/repository/ScrapRepository.java
  src/main/java/com/sparta/deventer/service/ScrapService.java
Labels: feat, refactor
